# Use postgres/example user/password credentials
version: '3.1'

services:
  app: 
    build: ./node
    user: "node"
    volumes:
      - ./node/app:/app
    working_dir: /app
    ports:
      - 8088:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres/database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080